# This is a basic workflow to help you get started with Actions

name: Test iOS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v1
    - name: Force xcode 11.4
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app
    - name: Dependencies
      run: |
        carthage update --platform iOS
        cp -r ./Carthage/Build/iOS/Alamofire.framework ./Frameworks/
        ls ./Frameworks/
    - name: build and test
      run: xcodebuild -project Peacemakr-iOS.xcodeproj -scheme Peacemakr-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.4.1' -only-testing:Peacemakr-iOS-Tests/SDKIntegrationTests -UseModernBuildSystem=NO test